### PR TITLE
[BACKLOG-36886] Fixed Input Fields on Login Page

### PR DESCRIPTION
**Pull request by AAravind27**
@pentaho/wcag,
Please review

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **333**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-832/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **333**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-832/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **333**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-832/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by AAravind27** [comment]
I raised a new PR

**Comment by dcleao** [comment]
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/833

**Pull request closed without merging**
