### PR TITLE
[BISERVER-14343] - PUC tab content gets truncated upon browser resize

### PR DESCRIPTION
**Pull request by RPAraujo**
@pentaho-lmartins please review

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 3m 8s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl widgets
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|315|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/gwt-widgets/job/PR-739/1/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by bennychow** [comment]
@RPAraujo Thanks for fixing this.  Can you clarify whether this is a regression caused by some other recent change?

**Comment by pentaho-lmartins** [comment]
@bennychow, the JIRA case says it is a regression, but we were unable to track the root cause.

**Comment by bennychow** [comment]
@pentaho-lmartins If a customer built their own theme, would these CSS changes be applied for them?

**Pull request merged**
