### PR TITLE
[BISERVER-12933] - Tooltip and shape visible of buttons 'Edit Content…

### PR DESCRIPTION
**Pull request by apratkin**
…', 'Save', 'Save As'

### CODE REVIEW

**Comment by apratkin** [comment]
Jira case with description about this problem (failed integration tests) and solution
http://jira.pentaho.com/browse/ENGOPS-2447

**Comment by apratkin** [comment]
@mbatchelor could you please review my commit?

**Comment by mchen-len-son** [comment]
Checked locally.
Having the specified fix applied, everything works - tests are passing.
Checkstyle is OK.
Merging.

**Comment by mchen-len-son** [comment]
@pamval @rfellows @bennychow please merge

**Pull request merged**
