### PR TITLE
[BACKLOG-36847] : Schedule perspective focus visibility

### PR DESCRIPTION
**Pull request by addagudi**

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 6m 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.gwt.widgets.client.toolbar.ToolbarButtonTest.testSetEnabled</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **378**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-849/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by phalguni-a — APPROVED** [review]

**Comment by addagudi** [comment]
@pentaho/wcag Please review

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **378**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-849/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **378**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-849/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by dcleao — APPROVED** [review]

**Pull request merged**
