### PR TITLE
[ANALYZER-3641] - Date Picker showing empty

### PR DESCRIPTION
**Pull request by CravoBranco**
* Analyzer's DatePicker changed according to UX recommendations:
- Removed calendar template to simplify the dialog.
- Alligned the labels and widgets to the left.
- Fixed Sapphire's theme display.

### CODE REVIEW

**Comment by CravoBranco** [comment]
@duarteteixeira , @pamval , @pentaho-lmartins , @mchen-len-son , @mbatchelor please review.
**Note:** This PR should be reviewed together with: https://github.com/pentaho/pentaho-analyzer/pull/1761

Change description:
* Analyzer's DatePicker changed according to UX recommendations:
- Removed calendar template to simplify the dialog.
- Alligned the labels and widgets to the left.
- Fixed Sapphire's theme display.

**Comment by pamval** [comment]
Since this is a change to a global theme css, we need to validate if we're not changing datepickers in other tools. Please check Report View, Dashboard Designer and PIR  just to be sure we do not regress on those areas.

**Comment by CravoBranco** [comment]
@pamval , thanks for your prompt response, I will check the components you mentioned.

**Comment by CravoBranco** [comment]
@pamval , I validated successfully the following use cases with the Sapphire theme:
- Create a new analyzer report, filter on a date and selecting a range from the date picker (i.e. base use case, in order to test the new calendar icon).
- Save and open analyzer reports.
- Create a new Interactive Reporting and filter on Date (white calendar icon is used).
- Add a dashboard designer, select prompts and click "+" (legacy calendar icon is used).

If I am missing some use case of set of use cases, please let me know. Thanks!

**Pull request merged**
