### PR TITLE
[BACKLOG-11682] -- removed hard styles for height and padding from gw…

### PR DESCRIPTION
**Pull request by krivera-pentaho**
…t dialog

### CODE REVIEW

**Comment by krivera-pentaho** [comment]
@mdamour1976 please review

**Comment by krivera-pentaho** [comment]
@mdamour1976 removed unused import as well.

**Comment by krivera-pentaho** [comment]
7.0.0.0 PR https://github.com/pentaho/pentaho-commons-gwt-modules/pull/434

**Comment by dkincade** [comment]
@krivera-pentaho please check out these changes in the SNAPSHOT build today and let me know if it all looks good. If so we will merge this into the 7.0.0.0 branch later today

**Pull request merged**
