### PR TITLE
[BACKLOG-35243] - Adding a capability to handle daylight savings time for daily schedule

### PR DESCRIPTION
**Pull request by rmansoor**

### CODE REVIEW

**Comment by rmansoor** [comment]
@ddiroma , @tkafalas  please review this PR

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
