### PR TITLE
[BISERVER-14291] - Append Timestamp to generated content option does not work on reports with no parameters

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins 
@ssamora 
@smmribeiro 

I did not write more unit test because GWT always mock internal packages so was impossible to test a result of JSONArray created inside the method for instance.

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **321**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/gwt-widgets/job/PR-776/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **321**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/gwt-widgets/job/PR-776/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bcostahitachivantara** [comment]
Sonnar issue related with diamons operator is because GWT not support JDK higher than java 6

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **321**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/gwt-widgets/job/PR-776/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ssamora — APPROVED** [review]

**Pull request merged**
