### PR TITLE
[BISERVER-13040]-Blockout time "Date" issue

### PR DESCRIPTION
**Pull request by denisprotopopov**
- now blockout time "day's" option enable for the first time

### CODE REVIEW

**Comment by denisprotopopov** [comment]
@mbatchelor please review the changes

**Comment by pamval** [comment]
@denisprotopopov isn't the bug the other way around?

I mean, if you're defining a daily blockout time, I expect to define start and end hour and that blockout time will apply every day. What would be the point of defining the day? If you want to specify the day, you choose a weekly blockout time.

So I think the bug is that the day box appears when editing. It should be hidden.

Does that make sense?

**Comment by denisprotopopov** [comment]
@pamval  please review the changes

**Comment by denisprotopopov** [comment]
@pamval please review the changes

**Pull request merged**
