### PR TITLE
[BACKLOG-5413] UI - Wrong background image is used in Data Source Wiz…

### PR DESCRIPTION
**Pull request by annapopova1**
…ard popup

The problem is overriding style #stepsPanel of globalCrystal.css with style of datasourceEditorDialog.css.
For fixing it I use more detailed selector for globalCrystal.css (for overriding).

Please review @plagoa @diogofscmariano @pamval @dkincade

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@plagoa, @diogofscmariano, @pamval,  @dkincade, could you please review it? the case has an SP twin targeted for the upcoming service pack.
Thanks!

**Comment by pamval** [comment]
I'm always a bit afraid of modifying the globalStyle.css. 

Are we sure #stepsPanel is only used in the context of .pentaho-dialog ?
Also, is this a regression ? Did we, for 6.0, change globalStyle.css to generalize #stepsPanel ? If so, why ?

**Comment by annapopova1** [comment]
@pamval 
It's a regression after 5.4. The #stepsPanel style also exists in datasourceEditorDialog.css (data-access module). The reason of regression is changing order of loading css resources. So for 5.4 globalCrystal.css is loaded after data-access but for 6.0 datasourceEditorDialog.css is loaded after globalCrystal.css and overrides style.
I can't find a reason of changing the order to include css on page.

**Comment by pamval** [comment]
do you know which commit introduced that order change ?

**Comment by annapopova1** [comment]
@pamval I don't know. I can't find a place where are imported css resources...

**Comment by pamval** [comment]
@plagoa please work with Anna and see if you both can find where these resources are being imported and why this has changed in 6.0

**Comment by annapopova1** [comment]
@pamval 
Our investigations (Paulo helped me):
1. We did not find out the reason of changing the order of importing css resources.
2. We have not found any other places where that css style is used.

As a result we have 2 suggestions:
1. The theme globalCrystal.css can override style from databaseEditorDialog.css (data-access plugin). Need add new detailed selector ".pentaho-dialog #stepsPanel" (without removing existing selector #stepsPanel).
2. We expect that importing resources works correctly now. It means first of all should be included themes and after that be included plugin's css. It provides ability to make customization for concrete plugin. To fix the issue we can move style from databaseEditorDialog.css (data-access plugin) to globalOnyx.css theme (because now onyx theme does not contain style for datasource wizard).

We checked both variants.
@pamval What do you think about our suggestions? Could you choose the most correct of them (after that I can change PR)?

**Comment by pamval** [comment]
2 seems more correct.

**Comment by annapopova1** [comment]
updated PR according second decision. Also sent PR for data-access https://github.com/pentaho/data-access/pull/680

**Comment by pamval** [comment]
@plagoa review and merge

**Comment by plagoa** [comment]
Looks good to me. I don't seem to have the necessary permissions to merge so @pamval or @diogofscmariano can you please merge?

**Pull request merged**
