### PR TITLE
BACKLOG-8067 - Toggle visibility of the attachment field

### PR DESCRIPTION
**Pull request by EgorZhuk**
Toggle visibility of the attachment field based on output type.
@tmorgner please take a look

### CODE REVIEW

**Comment by EgorZhuk** [comment]
@tmorgner @wingman-pentaho @lucboudreau seems to be it's another issue with wingman

**Comment by lucboudreau** [comment]
@tmorgner @EgorZhuk This is not a wingman issue. These tests are broken in all build environments. Please see if you can fix them.

http://sonar.pentaho.com:9000/dashboard/index/27279

**Comment by EgorZhuk** [comment]
@tmorgner @lucboudreau please see if the fix is acceptable

**Comment by tmorgner** [comment]
Not that your fix made any difference. Also: You cannot "fix" shared subfloor files. These files are under the control of the build team. Given that we have not changed anything in the build setup for the project, I have a feeling you will have to ask the build team to investigate. I'm pretty sure it comes down to a dependency problem or configuration problem on the servers.

**Comment by EgorZhuk** [comment]
@tmorgner it's not likely a problem on servers - it is reproducible on local machine too. It's easy to check - ant integration-test works like a charm, ant jacoco-integration fails.

The difference between those targets is that in the first case  <classpath refid="test.classpath"/> is used in the second  <classpath refid="inttest.classpath"/>.

The error is caused because GWTTestCase is not in classpath in the second case.

**Comment by tmorgner** [comment]
Aye. Lets hope the build team pushes out an update for the subfloor files soon. As said before: You cannot make local changes to them and hope that these survive the next push. Therefore we are officially 'discouraged' (ie do it at the risk of angering everyone who monitors subfloor or sonar) to make local changes to these files.

Its waiting time now, but it should not take long.

**Comment by tmorgner** [comment]
I'll merge this now - at least this way our build works until the next subfloor push, that hopefully will have the required change in.

**Comment by tmorgner** [comment]
@EgorZhuk can you rebase your branch? Or if easier, just push it without the commit that has the subfloor-gwt change - this change is now provided by the build team and causes the conflict here.

**Pull request merged**
