### PR TITLE
[TEST] - GWT unit tests

### PR DESCRIPTION
**Pull request by aliakseihaidukou**
@lucboudreau here is another portion of tests

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -f pentaho-gwt-widgets/build.xml clean-all resolve jacoco jacoco-integration checkstyle

Cleanup:
-------
rm -r ~/.ivy2/local || echo "no publish local to remove"

Changed files:
==============
  pentaho-gwt-widgets/build.properties
  pentaho-gwt-widgets/ivy.xml
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/i18n/WidgetsLocalizedMessages.java
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/i18n/WidgetsLocalizedMessages.properties
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/utils/Rectangle.java
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/utils/TimeUtil.java
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/wizards/AbstractWizardDialog.java
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/wizards/AbstractWizardPanel.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/CronEditor.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/NewBlockoutScheduleDialog.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/RecurrenceEditor.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/RunOnceEditor.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditor.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEmailWizardPanel.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleParamsWizardPanel.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleRecurrenceDialog.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/validators/CronEditorValidator.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/validators/RecurrenceEditorValidator.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/login/client/MantleLoginDialog.java
  pentaho-gwt-widgets/test-src/org/pentaho/gwt/widgets/client/utils/RectangleTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/gwt/widgets/client/utils/TimeUtilTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/gwt/widgets/client/wizards/AbstractWizardDialogTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/gwt/widgets/client/wizards/AbstractWizardPanelTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/gwt/widgets/client/wizards/WizardPanelListenerCollectionTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/CronEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/DailyRecurrenceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/MonthlyRecurrenceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/NewBlockoutScheduleDialogTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/RecurrenceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/RunOnceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditorWizardPanelTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEmailDialogTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEmailWizardPanelTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleParamsDialogTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleParamsWizardPanelTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleRecurrenceDialogTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/WeeklyRecurrenceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/YearlyRecurrenceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/BlockoutValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/CronEditorValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/DateRangeEditorValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/RecurrenceEditorValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/ScheduleEditorValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/events/SolutionFileActionEventTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/workspace/JsJobTriggerTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/login/client/MantleLoginDialogTest.java

Checkstyle violations:
======================
File pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/utils/TimeUtil.java
1. Message: Line has trailing spaces. at Line: 276 Column: None
2. Message: ',' is not followed by whitespace. at Line: 95 Column: 50

File pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditor.java
1. Message: Line has trailing spaces. at Line: 200 Column: None
2. Message: Line has trailing spaces. at Line: 202 Column: None
3. Message: '{' is not preceded with whitespace. at Line: 204 Column: 33
4. Message: Line has trailing spaces. at Line: 214 Column: None
5. Message: Line has trailing spaces. at Line: 453 Column: None
6. Message: '{' at column 3 should be on the previous line. at Line: 461 Column: 3
7. Message: Line has trailing spaces. at Line: 464 Column: None
8. Message: Line has trailing spaces. at Line: 73 Column: None

File pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleParamsWizardPanel.java
1. Message: Unused import - com.google.gwt.user.client.Window. at Line: 23 Column: 8

File pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleRecurrenceDialog.java
1. Message: Line has trailing spaces. at Line: 105 Column: None
2. Message: 'if' child have incorrect indentation level 10, expected level should be 8. at Line: 838 Column: None
3. Message: File contains tab characters (this is the first instance). at Line: 838 Column: 5


License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.gwt.widgets.client.utils.Rectangle:
 * branchPercentCoverage :70.83%
 * linePercentCoverage :83.33%
 * methodPercentCoverage :75.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :98.17%
    
org.pentaho.gwt.widgets.client.utils.Rectangle.Point:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%

**Comment by aliakseihaidukou** [comment]
@lucboudreau sorry, forgot to check /src folder. Done now

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -f pentaho-gwt-widgets/build.xml clean-all resolve jacoco jacoco-integration checkstyle

Cleanup:
-------
rm -r ~/.ivy2/local || echo "no publish local to remove"

Changed files:
==============
  pentaho-gwt-widgets/build.properties
  pentaho-gwt-widgets/ivy.xml
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/i18n/WidgetsLocalizedMessages.java
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/i18n/WidgetsLocalizedMessages.properties
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/utils/Rectangle.java
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/utils/TimeUtil.java
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/wizards/AbstractWizardDialog.java
  pentaho-gwt-widgets/src/org/pentaho/gwt/widgets/client/wizards/AbstractWizardPanel.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/CronEditor.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/NewBlockoutScheduleDialog.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/RecurrenceEditor.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/RunOnceEditor.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditor.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEmailWizardPanel.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleParamsWizardPanel.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleRecurrenceDialog.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/validators/CronEditorValidator.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/validators/RecurrenceEditorValidator.java
  pentaho-gwt-widgets/src/org/pentaho/mantle/login/client/MantleLoginDialog.java
  pentaho-gwt-widgets/test-src/org/pentaho/gwt/widgets/client/utils/RectangleTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/gwt/widgets/client/utils/TimeUtilTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/gwt/widgets/client/wizards/AbstractWizardDialogTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/gwt/widgets/client/wizards/AbstractWizardPanelTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/gwt/widgets/client/wizards/WizardPanelListenerCollectionTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/CronEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/DailyRecurrenceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/MonthlyRecurrenceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/NewBlockoutScheduleDialogTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/RecurrenceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/RunOnceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditorWizardPanelTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEmailDialogTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEmailWizardPanelTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleParamsDialogTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleParamsWizardPanelTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleRecurrenceDialogTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/WeeklyRecurrenceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/YearlyRecurrenceEditorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/BlockoutValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/CronEditorValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/DateRangeEditorValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/RecurrenceEditorValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/dialogs/scheduling/validators/ScheduleEditorValidatorTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/events/SolutionFileActionEventTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/client/workspace/JsJobTriggerTest.java
  pentaho-gwt-widgets/test-src/org/pentaho/mantle/login/client/MantleLoginDialogTest.java

Checkstyle violations:
======================
File pentaho-gwt-widgets/src/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditor.java
1. Message: 'array initialization' child have incorrect indentation level 8, expected level should be one of the following: 6, 52. at Line: 131 Column: None


License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.gwt.widgets.client.utils.Rectangle:
 * branchPercentCoverage :70.83%
 * linePercentCoverage :83.33%
 * methodPercentCoverage :75.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :98.17%
    
org.pentaho.gwt.widgets.client.utils.Rectangle.Point:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%

**Comment by lucboudreau** [comment]
Not sure why, but Wingman is only reporting an increase of coverage in two classes only. Are you sure that these tests are run by the build?

There are also checkstyle violations left.

**Comment by aliakseihaidukou** [comment]
@lucboudreau what coverage tool do you use? GWTMockito supports JaCoCo and Cobertura for sure.
And about checkstyle issue - what settings do you use? I checked with https://github.com/pentaho/pentaho-coding-standards/blob/master/pentaho_checkStyle.xml and this error didn't happen.

**Comment by lucboudreau** [comment]
For checkstyle, we're working on updating the definition file on GitHub. There are discrepencies we know of. Please fix the one found by Wingman to be sure.

As for the test coverage, we use Jacoco reports, then compare manually before and after. Could you do some checks to make sure that your tests do get accounted for in the coverage metrics? It'd be a shame it didn't.

**Comment by aliakseihaidukou** [comment]
@lucboudreau I updated the checkstyle issue manually.

About the coverage - part of the tests are GWT tests. According to GWT documentation we can use patched EMMA jar. No support for JaCoCo.
Most of the tests use GWTMockito framework - JaCoCo can't count these also. This framework modifies classes on the fly and JaCoCo can't find them.

**Pull request merged**
