### PR TITLE
[BACKLOG-36879][BACKLOG-37033][BACKLOG-37034] GWT/XUL Dialogs Default, Trap and Restore Focus

### PR DESCRIPTION
**Pull request by dcleao**
Part of PR set: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1617.

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **375**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-847/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by NJtwentyone — CHANGES_REQUESTED** [review]
please address sonarqube code smells https://sonar.orl.eng.hitachivantara.com/project/issues?id=org.pentaho%3Acommons-gwt&pullRequest=847&resolved=false&types=CODE_SMELL

for example:

- TODO comment
- function argument isn't used

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **375**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-847/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by NJtwentyone — APPROVED** [review]
Addressed code smells, only thing that sonar qube is complaining about is code coverage. But this is UI code, so reaching the treshold is not possible in all instances. Overall there are sufficient automated testing.

**Comment by dcleao** [comment]
Rewrote history to remove code review commits.

**Pull request merged**
