### PR TITLE
[SP-3339][PPP-3410]-Add an API to remove glasspane listeners

### PR DESCRIPTION
**Pull request by EgorZhuk**
#510 backport

### CODE REVIEW

**Comment by EgorZhuk** [comment]
@mchen-len-son @mbatchelor @tmorgner please merge

**Comment by EgorZhuk** [comment]
This one blocks other SP-339 PRs.

**Comment by EgorZhuk** [comment]
@tmorgner @pamval @mchen-len-son @mbatchelor could you, please, take a look?

**Comment by tmorgner** [comment]
I never thought that glasspanes can be that evil. PR is same as already merged one, minus the Wingman barf-up in the comments, therefore merged.

**Comment by EgorZhuk** [comment]
@tmorgner thank you!

**Pull request merged**
