### PR TITLE
[BACKLOG-11682] -- removed hard styles for height and padding from gw…

### PR DESCRIPTION
**Pull request by krivera-pentaho**
…t dialog

### CODE REVIEW

**Comment by krivera-pentaho** [comment]
@mdamour1976 @dkincade @kcruzada @pamval please review

**Comment by krivera-pentaho** [comment]
Master PR https://github.com/pentaho/pentaho-commons-gwt-modules/pull/433

**Comment by dkincade** [comment]
Waiting for Master PR review from @mdamour1976 before adding this to 7.0.0.0...

**Comment by krivera-pentaho** [comment]
There was no pentaho-server SNAPSHOT from 10/20. I am waiting for the next valid SNAPSHOT build to verify this change is included and fixes my issue.

**Comment by krivera-pentaho** [comment]
I verified that this is fixed in pentaho-server 7.0-SNAPSHOT#269

**Pull request merged**
