### PR TITLE
[BACKLOG-37104][BACKLOG-37161][BACKLOG-36972] Page Zoom (AA) - Base XUL/GWT Dialog Classes

### PR DESCRIPTION
**Pull request by dcleao**
@pentaho/wcag, please, review.

I believe it is best to review commit by commit.

In the end of the review will squash the _review_ commits with the corresponding _initial_ ones, to still maintain matters separate, before merging.

Related stories:
* [BACKLOG-37104 - Page Zoom (AA) - Base XUL/GWT Dialog Classes](https://hv-eng.atlassian.net/browse/BACKLOG-37104)
* [BACKLOG-37161 - Page Zoom (AA)- Focus Visible (AA) - Focus rectangle clipped at the top of responsive dialogs](https://hv-eng.atlassian.net/browse/BACKLOG-37161)
* [BACKLOG-36972 - Page Zoom (AA) - Change Password Dialog ](https://hv-eng.atlassian.net/browse/BACKLOG-36972)

Merge followed by:
* https://github.com/pentaho/pentaho-commons-xul/pull/219
* https://github.com/pentaho/pentaho-platform/pull/5262
* https://github.com/pentaho/pentaho-analyzer/pull/2378

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 7m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **398**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-873/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 47s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **398**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-873/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **398**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-873/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by mbrasil — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **398**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-873/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by davidmsantos90 — COMMENTED** [review]
Just found a small code style issue 👍🏼 

Also tested Analyzer with the latest commits and everything works like before 🎉

**Review by rmansoor — APPROVED** [review]

**Review by davidmsantos90 — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **398**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-873/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by dcleao** [comment]
Rewritten commits to squash the review commits into the corresponding original commit.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **398**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-873/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
