### PR TITLE
[BISERVER-10627] As an end user when a report run is in progress, I w…

### PR DESCRIPTION
**Pull request by EgorZhuk**
…ant to cancel it (Provide UI and implement JS logic)

Another simple change.

@tmorgner

### CODE REVIEW

**Comment by brosander** [comment]
Error building command: /home/brosander/pentaho-wingman/assembly/build/assembly-0.0.1/source/pentaho-commons-gwt-modules-base-373-717ba69a-85eb-4fc9-9caa-8738b4ff80fc/pom.xml (No such file or directory)

**Comment by EgorZhuk** [comment]
@tmorgner fixed method return type

**Comment by tmorgner** [comment]
@EgorZhuk Waiting for Wingman, Bryan needs to tweak its configuration to make it recognize the ant-file.

**Comment by brosander** [comment]
Error building command: /home/brosander/pentaho-wingman/assembly/build/assembly-0.0.1/source/pentaho-commons-gwt-modules-base-373-f0d5138e-4fb8-4f4d-b4e9-999c6e6223a6/pom.xml (No such file or directory)

**Comment by tmorgner** [comment]
Manually validated.

**Pull request merged**
