### PR TITLE
BACKLOG-11894--Combo-box on IE misses the corners of the box (new theme

### PR DESCRIPTION
**Pull request by kolinus**
Sapphire) - IE Only

What was done:
fixed dropdown widget for IE

### CODE REVIEW

**Comment by kolinus** [comment]
@DFieldFL could you please merge

**Comment by kurtwalker** [comment]
are those tests just failing on wingman?

**Comment by kolinus** [comment]
@kurtwalker well, target integration-test works fine, target jacoco-integration fails exactly as in wingman

**Comment by kolinus** [comment]
@DFieldFL  could you please review

**Pull request merged**
