### PR TITLE
[BACKLOG-36730] - UI changes to support OAUth 2.0

### PR DESCRIPTION
**Pull request by soagarwal1**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **330**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets-11/job/PR-820/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **330**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets-11/job/PR-820/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by NJtwentyone — COMMENTED** [review]
waiting to finish reviewing https://github.com/pentaho/pentaho-platform/pull/5185 before I approve or request changes

**Review by NJtwentyone — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 54m 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **330**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-820/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by dcleao — APPROVED** [review]

**Pull request merged**
