### PR TITLE
[BACKLOG-36883] xul tag: <toolbarbutton>:: Functional images don't provide text alternative

### PR DESCRIPTION
**Pull request by NJtwentyone**
- add ToolbarButton#setImageAltText and ToolbarButton#getImageAltText

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **336**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-846/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **362**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-846/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by NJtwentyone** [comment]
I need to update the commit message to sync up with splitting this jira issue into several. I will resolve this when I address peer review comments

**Review by soagarwal1 — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **362**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-846/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by NJtwentyone** [comment]
@pentaho/wcag  please review

**Review by rmansoor — APPROVED** [review]

**Pull request merged**
